# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: script.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='script.proto',
  package='script',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x0cscript.proto\x12\x06script\"+\n\nwvs_script\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c'
)




_WVS_SCRIPT = _descriptor.Descriptor(
  name='wvs_script',
  full_name='script.wvs_script',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='script.wvs_script.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='script.wvs_script.content', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['wvs_script'] = _WVS_SCRIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

wvs_script = _reflection.GeneratedProtocolMessageType('wvs_script', (_message.Message,), {
  'DESCRIPTOR' : _WVS_SCRIPT,
  '__module__' : 'script_pb2'
  # @@protoc_insertion_point(class_scope:script.wvs_script)
  })
_sym_db.RegisterMessage(wvs_script)


# @@protoc_insertion_point(module_scope)
